language: python
python:
  #- "2.7"
  - "3.6"
  
env:
  global:
    - ROLE_DIR=$(pwd)/roles
    - ROLE_NAME="configure-lvm-storage"
    
services:
  - docker

install:
  - pip install molecule docker

script:
  - cd ${ROLE_DIR}/${ROLE_NAME}
  - molecule lint
  - molecule syntax
