language: python
python:
  #- "2.7"
  - "3.6"
  
env:
  global:
    - ROLE_DIR=./roles
    - ROLE_NAME=centos_toolchain
    
services:
  - docker

install:
  - pip install molecule docker

script:
  - cd ./${ROLE_DIR}/${ROLE_NAME}
  - molecule --debug test
