language: python
python:
  #- "2.7"
  - "3.6"
  
env:
  global:
    - ROLE_DIR=./roles
    
services:
  - docker

install:
  - pip install molecule docker

script:
  - cd ./${ROLE_DIR}/centos_toolchain
  - molecule lint
  - molecule syntax
