language: python
python:
  - "2.7"
  - "3.6"
  
env:
  global:
    - ROLE_DIR=./roles
    
services:
  - docker

install:
  - pip install molecule docker

script:
  - ls -lah
  - molecule --version
  - cd ./${ROLE_DIR}/centos_toolchain
  - molecule test
