language: python

services:
  - docker

before_install:
  - ls -lah
  - docker pull quay.io/ansible/molecule
  - alias molecule$(docker run --rm -it -v "$(pwd)":/tmp/$(basename "${PWD}"):ro -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/$(basename "${PWD}") quay.io/ansible/molecule:2.22 molecule)
script:
  - molecule --version
  - docker ps -a
